build: off

clone_folder: c:\gopath\src\github.com\wk8\go-win-iscsidsc

environment:
  GOPATH: c:\gopath

  matrix:
    # see https://www.appveyor.com/docs/windows-images-software/#golang
    - GOROOT: C:\go
      GO_WIN_ISCSI_GOBIN: c:\go\bin\go

    - GOROOT: C:\go112
      GO_WIN_ISCSI_GOBIN: c:\go112\bin\go

    - GOROOT: C:\go111
      GO_WIN_ISCSI_GOBIN: c:\go111\bin\go

cache:
  # contains glide's cache
  - '%USERPROFILE%\.glide'

before_test:
  - powershell -File hack/start_iscsi_services.ps1
  - powershell -File hack/deps.ps1

test_script:
  - powershell -File hack/unit_tests.ps1
  - powershell -File hack/integration_tests.ps1
  - powershell -File hack/lint.ps1 -UpdateTools

after_test:
  - powershell -File hack/teardown_iscsi_targets.ps1
