# TODO wkpo: test several go versions? see https://www.appveyor.com/docs/windows-images-software/#golang

build: off

clone_folder: c:\go\src\github.com\wk8\go-win-iscsidsc

environment:
  GOPATH: c:\go

cache:
  # contains glide's cache
  - '%USERPROFILE%\.glide'

before_test:
  - powershell -File hack/start_iscsi_services.ps1
  - powershell -File hack/deps.ps1

test_script:
  - powershell -File hack/unit_tests.ps1
  - powershell -File hack/integration_tests.ps1

after_test:
  - powershell -File hack/teardown_iscsi_targets.ps1
